services:
  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    container_name: mtproto-proxy
    restart: always
    ports:
      - "8443:443"
    volumes:
      - proxy-config:/data

volumes:
  proxy-config:
